name: .NET Core Matrix Build

on: [push, pull_request]

jobs:
  build-test:
    name: Debug Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: ['2.2.103', '3.0', '3.1']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ matrix.dotnet }} on ${{ matrix.os }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: |
        dotnet build
        dotnet test --no-build Lab.Tests/Lab.Tests.csproj
