name: .NET Core Matrix Build

on: [push, pull_request]

jobs:
  build-test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet: ['3.1.403', '3.0', '3.1.100']
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core ${{ matrix.dotnet }} on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build with dotnet
      run: |
        dotnet build Lab/
        dotnet test --no-build Lab/Lab.Tests/Lab.Tests.csproj
